# Monthly Contribution Strategy Configuration
# Designed for $10,000 initial capital with $500 monthly contributions

name: "Monthly Contribution Multi-Indicator Strategy"
description: |
  A robust trading strategy combining technical indicators (RSI, Bollinger Bands, VWAP) 
  with market sentiment (Fear & Greed Index) for consistent growth with monthly contributions.
  Implements dynamic position sizing, risk management, and maintains a 20-30% cash reserve.

# Account Configuration
account:
  initial_capital: 10000
  monthly_contribution: 500
  contribution_day: 1  # First day of each month
  cash_reserve_target: 0.25  # 25% target cash reserve
  rebalance_quarterly: true

# Entry Rules - Multiple conditions combined with AND/OR logic
entry_rules:
  # Rule 1: Oversold Bounce
  - name: "Oversold Bounce"
    operator: "and"
    conditions:
      - left: "rsi"
        operator: "<"
        right: 30
      - left: "close"
        operator: "<"
        right: "bb_lower"
      - left: "volume"
        operator: ">"
        right: "volume_sma_20"
    
  # Rule 2: Bollinger Band Squeeze Breakout
  - name: "BB Squeeze Breakout"
    operator: "and"
    conditions:
      - left: "bb_width"
        operator: "<"
        right: 0.01  # 1% squeeze threshold
      - left: "close"
        operator: "cross_above"
        right: "bb_upper"
      - left: "volume"
        operator: ">"
        right: "volume_sma_20"
    
  # Rule 3: VWAP Institutional Support
  - name: "VWAP Support"
    operator: "and"
    conditions:
      - left: "close"
        operator: ">"
        right: "vwap"
      - left: "close"
        operator: "cross_above"
        right: "vwap"
      - left: "vwap_bands_width"
        operator: "<"
        right: 0.02
    
  # Rule 4: Extreme Fear Entry
  - name: "Extreme Fear Entry"
    operator: "and"
    conditions:
      - left: "fear_greed"
        operator: "<"
        right: 25
      - left: "rsi"
        operator: "<"
        right: 40

# Exit Rules
exit_rules:
  # Rule 1: Overbought Exit
  - name: "Overbought Exit"
    operator: "and"
    conditions:
      - left: "rsi"
        operator: ">"
        right: 70
      - left: "close"
        operator: ">"
        right: "bb_upper"
    
  # Rule 2: VWAP Resistance
  - name: "VWAP Resistance"
    operator: "and"
    conditions:
      - left: "close"
        operator: "<"
        right: "vwap"
      - left: "close"
        operator: "cross_below"
        right: "vwap"
    
  # Rule 3: Extreme Greed Exit
  - name: "Extreme Greed Exit"
    operator: "and"
    conditions:
      - left: "fear_greed"
        operator: ">"
        right: 75
      - left: "rsi"
        operator: ">"
        right: 60
    
  # Rule 4: Bollinger Band Mean Reversion
  - name: "BB Mean Reversion"
    operator: "and"
    conditions:
      - left: "close"
        operator: "cross_below"
        right: "bb_middle"
      - left: "position_profit_pct"
        operator: ">"
        right: 0.05  # 5% profit

# Market Regime Filters
filters:
  # Filter 1: Avoid extreme volatility
  - name: "Volatility Filter"
    operator: "and"
    conditions:
      - left: "atr_pct"
        operator: "<"
        right: 0.05  # ATR less than 5% of price
  
  # Filter 2: Minimum liquidity
  - name: "Liquidity Filter"
    operator: "and"
    conditions:
      - left: "volume"
        operator: ">"
        right: 1000000  # Minimum 1M shares volume
      - left: "dollar_volume"
        operator: ">"
        right: 10000000  # Minimum $10M dollar volume
  
  # Filter 3: Trend alignment
  - name: "Trend Filter"
    operator: "or"
    conditions:
      - left: "sma_50"
        operator: ">"
        right: "sma_200"  # Uptrend
      - left: "rsi"
        operator: "<"
        right: 30  # Or oversold condition

# Position Sizing Configuration
position_sizing:
  method: "kelly"  # Kelly Criterion with safety constraints
  size: 0.25  # Maximum 25% Kelly fraction
  max_position: 0.15  # Maximum 15% of portfolio per position
  scale_in: true  # Allow scaling into positions
  scale_out: true  # Allow scaling out of positions
  
  # Kelly Criterion adjustments
  kelly_adjustments:
    volatility_factor: true  # Reduce size in high volatility
    win_rate_minimum: 0.40  # Minimum 40% win rate to use Kelly
    safety_multiplier: 0.5  # Apply 50% safety factor to Kelly

# Risk Management Configuration
risk_management:
  stop_loss: 0.02  # 2% stop loss
  stop_loss_type: "percent"
  take_profit: 0.10  # 10% take profit
  take_profit_type: "percent"
  trailing_stop: 0.03  # 3% trailing stop
  time_stop: 20  # Exit after 20 days if no profit
  max_loss_per_trade: 0.02  # Maximum 2% account risk per trade
  max_daily_loss: 0.06  # Maximum 6% daily loss
  max_positions: 8  # Maximum 8 concurrent positions

# Indicator Parameters
indicators:
  rsi:
    period: 14
    overbought: 70
    oversold: 30
    
  bollinger_bands:
    period: 20
    std_dev: 2
    squeeze_threshold: 0.01
    
  vwap:
    anchor: "session"  # Session VWAP
    bands_std: 1.5
    
  fear_greed:
    source: "alternative"  # Use Alternative.me API
    extreme_fear: 25
    extreme_greed: 75
    
  moving_averages:
    sma_20: 20
    sma_50: 50
    sma_200: 200
    volume_sma: 20

# Rebalancing Configuration
rebalancing:
  enabled: true
  frequency: "quarterly"  # Quarterly rebalancing
  threshold: 0.20  # Rebalance if position exceeds 20%
  target_allocation: "equal_weight"  # Equal weight across positions
  
  # Sector rotation settings
  sector_rotation:
    enabled: true
    sectors:
      - "XLK"  # Technology
      - "XLF"  # Financials
      - "XLV"  # Healthcare
      - "XLE"  # Energy
      - "XLI"  # Industrials
      - "XLY"  # Consumer Discretionary
      - "XLP"  # Consumer Staples
      - "XLRE" # Real Estate
    max_per_sector: 0.30  # Maximum 30% per sector

# Performance Tracking
performance:
  benchmark: "SPY"  # S&P 500 benchmark
  reporting_frequency: "monthly"
  metrics_tracked:
    - win_rate
    - sharpe_ratio
    - max_drawdown
    - profit_factor
    - average_return
    - contribution_impact
    
# Backtesting Parameters
backtest:
  start_date: "2020-01-01"
  end_date: "2024-01-01"
  data_frequency: "daily"
  slippage: 0.001  # 0.1% slippage
  commission: 0.0  # Assuming commission-free trading
  
  # Monte Carlo simulation
  monte_carlo:
    enabled: true
    simulations: 1000
    confidence_level: 0.95